feat: change the menu to add a note
onlynotes-swent/onlynotes pull request #175
Opened 2024-11-25 11:53 UTC by MatthieuSLR9

# Description

I changed the way you would add a new note by removing the addNote Screen and simply adding a popup that asks for a name and the visibility is set to private by default.

Fixes # (issue)

# How Has This Been Tested?
  
### UI Tests

Ui tests for addNote.

### End to end Tests

  
# Dependencies

Please describe the dependencies 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged in downstream modules, no conflicts with main

2024-11-25 15:00 UTC, LawrenceLeitgib requested changes
Overall good code but I had some trouble with the UI, the button's text aren't displayed correctly, I think we should fix that before merging
![Screenshot_20241125_155826](https://github.com/user-attachments/assets/800b9298-47a4-456a-81cc-d1233e7bca9f)

2024-11-25 15:00 UTC, LawrenceLeitgib commented on app/src/main/java/com/github/onlynotesswent/ui/common/Popups.kt
> +fun CreationDialog(
Good idea to modularize all of that (evoiding duplicate code)

2024-11-25 15:00 UTC, LawrenceLeitgib commented on app/src/main/java/com/github/onlynotesswent/ui/overview/FolderContent.kt
> +            NoteDialog(
Good code, this is very is to maintain

2024-11-25 15:00 UTC, LawrenceLeitgib commented on app/src/main/java/com/github/onlynotesswent/ui/overview/Overview.kt
> +          NoteDialog(
This code is the same as the one in Overview , but I think it's fine to leave it as is. Extracting the common code would make too much modularization, which might only make the code messier.

2024-11-25 15:17 UTC, LawrenceLeitgib commented
I also found another bug, that the pop-up "discard unsaved change" still apear even after saving changes it also doesn't appear if I modify something. This bug only appear after creating a new note.
[Screen_recording_20241125_161707.webm](https://github.com/user-attachments/assets/cede902a-67e3-4770-aae3-05590d1ff671)

2024-11-25 17:10 UTC, MatthieuSLR9 commented
> I found another bug, that the pop-up "discard unsaved change" still apear even after saving changes it also doesn't appear if I modify something. This bug only appear after creating a new note. Also when I creat a new note and save it, the course is still Swent while it should be empty. Also when I click on save after editing the note it should redirect me on overview and not keep me on the page [Screen_recording_20241125_161707.webm](https://github.com/user-attachments/assets/cede902a-67e3-4770-aae3-05590d1ff671)

I did not modify the new UI edit note screen as I did not work on it but I will work on it now as part of my PR to address these issues.


> And also the addNote page is not used anymore so I think we can safely delet it

I kept it just in case we wanted to revert back to it in the future. I also left the tests for it. But I will delete it if you think it is better.

2024-11-25 18:13 UTC, robertaleG submitted a review, later dismissed

2024-11-25 18:21 UTC, robertaleG commented on app/src/androidTest/java/com/github/onlynotesswent/ui/overview/OverviewTest.kt
> +    composeTestRule.onNodeWithTag("confirmNoteAction").assertIsDisplayed()
Also don't forget to verify correct calls to navigation actions / view models or repositories are made, 
... to actually test the callbacks

2024-11-28 18:09 UTC, Roshan-y commented
> Overall good code but I had some trouble with the UI, the button's text aren't displayed correctly, I think we should fix that before merging ![Screenshot_20241125_155826](https://private-user-images.githubusercontent.com/74073228/389582841-800b9298-47a4-456a-81cc-d1233e7bca9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTc0MTcsIm5iZiI6MTczMjgxNzExNywicGF0aCI6Ii83NDA3MzIyOC8zODk1ODI4NDEtODAwYjkyOTgtNDdhNC00NTZhLTgxY2MtZDEyMzNlN2JjYTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE4MDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZGEwNTkzY2Y5ZWY3ZDI2NTljYmFlYWY0MGMyNjU0NmEyYjRiMjU4ZDc5MjgxNjI2MTgyYTQwZGQyMDQ2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uploSIAVEkZGSFm1P769m8qzADEDmk1X-JNxL0-RoUs)
> 
> I found another bug, that the pop-up "discard unsaved change" still apear even after saving changes it also doesn't appear if I modify something. This bug only appear after creating a new note. Also when I creat a new note and save it, the course is still Swent while it should be empty. Also when I click on save after editing the note it should redirect me on overview and not keep me on the page [Screen_recording_20241125_161707.webm](https://github.com/user-attachments/assets/cede902a-67e3-4770-aae3-05590d1ff671)
> 
> And also the addNote page is not used anymore so I think we can safely delet it

Hey I fixed the first bug, it was due to trying to save a default course in documentSnapshotToNote in NoteRepositoryFirestore.kt file. The second one, was a decisions I made. I thought maybe the user would want to add a comment or modify the pdf or markdown after saving the metadata so I made it so that they stay in the page

2024-11-28 19:10 UTC, Roshan-y commented
> > I kept it just in case we wanted to revert back to it in the future. I also left the tests for it. But I will delete it if you think it is better.
> 
> it's as you want but I think we can alway goes back to old commit if we want to revert some changes

I removed add note as I think it's unnecessary to keep it

2024-11-28 19:11 UTC, Roshan-y commented on app/src/androidTest/java/com/github/onlynotesswent/ui/overview/OverviewTest.kt
> +    composeTestRule.onNodeWithTag("confirmNoteAction").assertIsDisplayed()
Yes good catch

2024-11-28 23:02 UTC, LawrenceLeitgib approved these changes
Nice changes and fix to the the discard changes pop up, for the UI bug this will indeed be fixed in another PR as this PR was about add note and not edit note

2024-11-28 23:15 UTC, merged