Fix: fix navigation back stack issues and bugs
onlynotes-swent/onlynotes pull request #181
Opened 2024-11-27 11:00 UTC by AvillegasH

# Description

In this PR the focus was in the navigation aspect of the app. Some bugs were found because we were not using the back stack appropriately, but now all these issues have been addressed. 
Before, to navigate between public profiles or within a folder hierarchy, we implemented our own navigation stack, to which we pushed and popped `userId` and `folderId` to then recompute screens with the corresponding user or folder Id. However, this solution was not optimal since it did not take into account the hardware back button of the device, and some bugs occurred by using this button. To fix this, we went back to the back stack implementation provided by the `NavController`. 
So we added an argument parameter to the FolderContent (`"Folder Contents Screen/{folderId}"`) and  PublicProfile (`"Public Profile Screen/{userId}"`) screen routes and modified it accordingly when navigating to these screens. Then, inside the `NavHost` in `MainActivity` we extract the `userId` or the `folderId` argument from the `navBackStackEntry` and we navigate to the corresponding screen whenever these values change.

Another bug that was addressed was pressing the back button after logging out or deleting account. Before this would bring us to our profile screen which was clearly wrong. This behavior has been corrected by adding a `BackHandler` in the SignIn screen, so now clicking the back button in the SignIn screen will close the app.  

Finally, some exit transitions were added when going back from one screen to another and an enter  transition was added to the FolderContents screen. Additionally, minor changes were performed to the CustonLazyGrid to slightly improve its performance.

Fixes #126 

# How Has This Been Tested?

Some tests were added to check the correct behavior of the back button when in the SignIn screen, and other tests have been adapted to the use of the  navigation back stack

### Unit Tests

Some unit tests were adapted to the use of the back stack
  
### UI Tests

A new UI test in SignInTest was added to check the correct behavior of the back button

### End to end Tests

No end  to end tests added
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged in downstream modules, no conflicts with main

2024-11-28 21:01 UTC, Roshan-y requested changes
Overall very well written and tested. I added a suggestion to tests to remove some repetitive code. I also was wondering why you call `folderViewModel.getFolderById(folderId)` and `userViewModel.refreshProfileUser(userId)` in main and not in their respective screens.

2024-11-28 21:25 UTC, AvillegasH commented on app/src/androidTest/java/com/github/onlynotesswent/ui/overview/FolderContentTest.kt
> +    folderViewModel.selectedFolder(folder)
Nice suggestion. I wanted to have different folder options for the folder contents screen to display and I moved it out of the setUp() but forgot to extract it as another function. Nice catch!

2024-11-28 21:49 UTC, AvillegasH commented on app/src/main/java/com/github/onlynotesswent/MainActivity.kt
> +            LaunchedEffect(folderId) {
The thing is that the folderId/userId are passed as parameters in the back stack entry so there is no way to get them directly in their respective screens unless we add another argument to the screens (folderId: Folder? and userId: User? respectively). Do you think we should do that or leave it as is?

2024-11-29 00:47 UTC, Roshan-y commented on app/src/main/java/com/github/onlynotesswent/MainActivity.kt
> +            LaunchedEffect(folderId) {
True, it could also cause problem by keeping selectedFolder as null and therefore not showing screen and not having the launched effect.

2024-11-29 00:50 UTC, Roshan-y approved these changes
Good job addressing my requests

2024-11-29 00:50 UTC, merged