Bugfix: remove deprecated GoogleSignIn and refactor sign in
onlynotes-swent/onlynotes pull request #186
Opened 2024-11-29 03:45 UTC by santiagoarayaramos

Completely removed the use of the deprecated GoogleSignIn, using Credential Manager instead. This also involved a lot of refactoring to increase readability of the code, and move most code to the renamed Authenticator file (instead of defining it in Sign In). This now handles sign in with credential manager (using google's federated identity), and authentication with Firebase Auth.

The Authenticator is also moved out of the sign in class to enable correct logout (including the resetting of the credential manager state) in profile screens.

Finally, replaced the creation of unmanaged unconnected coroutines with safer coroutines connected to the composable functions they are called in.

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Please delete non applicable test types.

### Unit Tests
  
### UI Tests

### End to end Tests

  
# Dependencies

Please describe the dependencies 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged in downstream modules, no conflicts with main

2024-12-07 18:13 UTC, aaisel requested changes
Overall good job at tackling the previous issues that we had. Your code is well structured and easy to understand, comments are clear and useful. We can merge this even if the coverage is not enough - testing sign in is difficult, and there is no point in wasting a lot of time on it. 
I only requested a few minor changes about updating the comments and removing some Toasts.

2024-12-07 18:13 UTC, aaisel commented on app/src/main/java/com/github/onlynotesswent/ui/user/PublicProfile.kt
> +    authenticator: Authenticator,
Update comments 😸

2024-12-07 18:13 UTC, aaisel commented on app/src/main/java/com/github/onlynotesswent/ui/user/PublicProfile.kt
> +    authenticator: Authenticator,
Update comments 😆

2024-12-07 18:13 UTC, aaisel commented on app/src/main/java/com/github/onlynotesswent/ui/user/PublicProfile.kt
> + * @param authenticator The Authenticator used for the app, to enable sign out of the user.
Awesome job at updating the doc 🎊

2024-12-07 18:13 UTC, aaisel commented on app/src/test/java/com/github/onlynotesswent/model/authentication/AuthenticatorTest.kt
> +// package com.github.onlynotesswent.model.authentication
As mentioned above, testing sign in is difficult. Coverage is good enough, tests not used and commented out could be removed

2024-12-08 05:13 UTC, santiagoarayaramos commented on app/src/main/java/com/github/onlynotesswent/ui/user/PublicProfile.kt
> +    authenticator: Authenticator,
Nice catch!!

2024-12-09 10:43 UTC, aaisel commented
Great job at addressing requested changes!

2024-12-09 10:44 UTC, merged