feature: implement the back end for play flashcard
onlynotes-swent/onlynotes pull request #215
Opened 2024-12-09 13:14 UTC by LawrenceLeitgib

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Please delete non applicable test types.

### Unit Tests
  
### UI Tests

### End to end Tests

  
# Dependencies

Please describe the dependencies 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged in downstream modules, no conflicts with main

2024-12-09 18:10 UTC, robertaleG requested changes
The PR is missing some docs and needs some minor tweaks.  The User MVVM  tests are also a bit all over the place (unnecessary assertions and missing necessary ones).  Apart from that you did a good job 👍

2024-12-09 18:14 UTC, robertaleG commented on app/src/test/java/com/github/onlynotesswent/model/user/UserViewModelTest.kt
> +    userViewModel.updateUserFlashcard(flashcard)
forgot to put int the review but you did the same again for the delete function, I think it shouldn't be necessary and will just slow down the CI. a default value {} for a callback parameter can't really fail a test

2024-12-10 09:36 UTC, LawrenceLeitgib commented on app/src/test/java/com/github/onlynotesswent/model/user/UserViewModelTest.kt
> +    userViewModel.getUserFlashcardFromDeck(deck, { assert(false) })
I am testing the if statement inside the update methode

2024-12-10 23:02 UTC, robertaleG approved these changes
Very nice changes, well done. I will merge

2024-12-10 23:02 UTC, merged