Bugfix/ci
onlynotes-swent/onlynotes pull request #22
Opened 2024-10-07 08:44 UTC by Roshan-y

2024-10-07 12:45 UTC, robertaleG commented on .github/workflows/sonarcloud.yml
> +      # Caching is a very useful part of a CI, as a workflow is executed in a clean environement every time,
_environment_ is spelled _environment_ not _environement_

2024-10-07 13:29 UTC, robertaleG requested changes
The code works and solves the CI issue. There is still an issue with sonar cloud. I recommend you try to add this line in _AndroidManifest.xml_ :
```
<application
    android:usesCleartextTraffic="false"   // add this line
    ... >
    ...
</application>
```
This should neutralise the warning.

Also, please correct the spelling mistake on line 49. 
After making those changes and if they pass, we can merge your PR.

2024-10-10 09:01 UTC, aaisel commented on .github/workflows/sonarcloud.yml
>        # To avoid that, we cache the the gradle folder to reuse it later.
Remove comment

2024-10-10 09:05 UTC, aaisel commented
Merging this to enable CI

2024-10-10 09:06 UTC, aaisel approved these changes

2024-10-10 09:07 UTC, merged