Google Authentication screen
onlynotes-swent/onlynotes pull request #39
Opened 2024-10-10 12:57 UTC by robertaleG

Simple google auth screen conforms with Figma and redirects to Overview screen. Once user fetching with email is done, we can change it to redirect to profile creation screen or overview.

2024-10-11 11:43 UTC, Roshan-y requested changes
Code written well, remove the unnecessary comments (I added as a comment in review) and add more tests to pass 80% code coverage

2024-10-11 11:43 UTC, Roshan-y commented on app/src/androidTest/java/com/github/onlynotesswent/ui/authentication/LoginTest.kt
> +
The comment from line 3 to 9 is unnecessary and should be removed

2024-10-15 09:07 UTC, Roshan-y requested changes
Code well written, need to delete Authentication.kt as it is not used anymore

2024-10-15 09:20 UTC, robertaleG commented on app/src/main/java/com/github/onlynotesswent/MainActivity.kt
> -      composable(Screen.AUTH) { AuthenticationScreen(navigationActions) }
Changes were addressed in latest commit.

2024-10-15 09:25 UTC, Roshan-y approved these changes

2024-10-15 12:13 UTC, merged